// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmizbtbzvsbnczrjwnfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtaXpidGJ6dnNibmN6cmp3bmZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTgxOTAsImV4cCI6MjA2OTg5NDE5MH0.4xyhKkpMUdapLRfzrTgmHY_Ry_Dym9kFOwWiicwEFZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});